/*
In this program, the value generated by noise() is already seeded, 
and does not change without reloading the window.
What is done in this program is to change the focus,
where you start watching it
*/

let inc = 0.01;

// a variable to change the focus of the seeded value in draw()
let start = 0;

function setup() {
  createCanvas(400, 400);
}

function draw() {
  background(51);
  noFill();

  // draw a wave in full screen
  beginShape();
  let xoff = start;
  for (let x = 0; x < width; x++) {
    stroke(255);
    let y = noise(xoff) * height;
    vertex(x, y);
    xoff += inc;
  }
  endShape();
  // make noise() return different values in the next draw loop
  start += inc;
}
